export const WEBHOOK_GET_BARANG = import.meta.env.VITE_WEBHOOK_GET_BARANG
export const WEBHOOK_INPUT_PO_V3 = import.meta.env.VITE_WEBHOOK_INPUT_PO_V3
export const WEBHOOK_LIST_PO = import.meta.env.VITE_WEBHOOK_LIST_PO
export const WEBHOOK_UPDATE_SISA_MODAL = import.meta.env.VITE_WEBHOOK_UPDATE_SISA_MODAL
export const WEBHOOK_PAYMENT_PROOF = import.meta.env.VITE_WEBHOOK_PAYMENT_PROOF
export const WEBHOOK_STRUK_PEMBELIAN_KASPIN = import.meta.env.VITE_WEBHOOK_STRUK_PEMBELIAN_KASPIN
export const WEBHOOK_FINANCE_VERIF_PO = import.meta.env.VITE_WEBHOOK_FINANCE_VERIF_PO
